<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Organic Baby Spinach',
                'slug' => Str::slug('Organic Baby Spinach'),
                'description' => 'Tươi ngon, sạch, được trồng theo tiêu chuẩn hữu cơ.',
                'price' => 45000,
                'sale_price' => 39000,
                'weight' => '200',
                'unit' => 'g',
                'stock_quantity' => 100,
                'view_count' => 0,
                'category_id' => 10,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Norwegian Salmon Fillet',
                'slug' => Str::slug('Norwegian Salmon Fillet'),
                'description' => 'Phi lê cá hồi Nauy, giàu Omega-3.',
                'price' => 230000,
                'sale_price' => 215000,
                'weight' => '300',
                'unit' => 'g',
                'stock_quantity' => 80,
                'view_count' => 0,
                'category_id' => 14,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Ribeye Beef Steak (USDA Choice)',
                'slug' => Str::slug('Ribeye Beef Steak (USDA Choice)'),
                'description' => 'Thịt bò Mỹ cao cấp, thích hợp cho món beefsteak.',
                'price' => 310000,
                'sale_price' => 285000,
                'weight' => '500',
                'unit' => 'g',
                'stock_quantity' => 60,
                'view_count' => 0,
                'category_id' => 12,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => '100% Orange Juice – Tropicana',
                'slug' => Str::slug('100% Orange Juice – Tropicana'),
                'description' => 'Nước cam ép nguyên chất từ thương hiệu Tropicana.',
                'price' => 35000,
                'sale_price' => 32000,
                'weight' => '1',
                'unit' => 'l',
                'stock_quantity' => 120,
                'view_count' => 0,
                'category_id' => 22,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Vinamilk Fresh Milk (No Sugar)',
                'slug' => Str::slug('Vinamilk Fresh Milk (No Sugar)'),
                'description' => 'Sữa tươi Vinamilk không đường, thanh mát tự nhiên.',
                'price' => 28000,
                'sale_price' => null,
                'weight' => '1',
                'unit' => 'l',
                'stock_quantity' => 200,
                'view_count' => 0,
                'category_id' => 24,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Omachi Instant Noodles – Spicy Shrimp',
                'slug' => Str::slug('Omachi Instant Noodles – Spicy Shrimp'),
                'description' => 'Mì Omachi tôm chua cay, sợi khoai tây.',
                'price' => 7000,
                'sale_price' => null,
                'weight' => '80',
                'unit' => 'g',
                'stock_quantity' => 300,
                'view_count' => 0,
                'category_id' => 18,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Pork Belly (Ba Rọi Heo)',
                'slug' => Str::slug('Pork Belly (Ba Rọi Heo)'),
                'description' => 'Ba rọi heo tươi, thích hợp kho, chiên, nướng.',
                'price' => 110000,
                'sale_price' => 98000,
                'weight' => '500',
                'unit' => 'g',
                'stock_quantity' => 90,
                'view_count' => 0,
                'category_id' => 11,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Oreo Original Biscuits 137g',
                'slug' => Str::slug('Oreo Original Biscuits 137g'),
                'description' => 'Bánh quy Oreo truyền thống, thơm ngon.',
                'price' => 22000,
                'sale_price' => null,
                'weight' => '137',
                'unit' => 'g',
                'stock_quantity' => 200,
                'view_count' => 0,
                'category_id' => 29,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Kale Leaves (Cải xoăn hữu cơ)',
                'slug' => Str::slug('Kale Leaves (Cải xoăn hữu cơ)'),
                'description' => 'Cải xoăn tươi, chứa nhiều vitamin và chất xơ.',
                'price' => 38000,
                'sale_price' => null,
                'weight' => '200',
                'unit' => 'g',
                'stock_quantity' => 110,
                'view_count' => 0,
                'category_id' => 10,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Chicken Breast (Fillet)',
                'slug' => Str::slug('Chicken Breast (Fillet)'),
                'description' => 'Ức gà tươi, không da, giàu protein.',
                'price' => 85000,
                'sale_price' => 78000,
                'weight' => '500',
                'unit' => 'g',
                'stock_quantity' => 150,
                'view_count' => 0,
                'category_id' => 13,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'G7 Instant Coffee 3-in-1',
                'slug' => Str::slug('G7 Instant Coffee 3-in-1'),
                'description' => 'Cà phê hòa tan G7 đậm đà, tiện lợi.',
                'price' => 34000,
                'sale_price' => null,
                'weight' => '240',
                'unit' => 'g',
                'stock_quantity' => 300,
                'view_count' => 0,
                'category_id' => 23,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Fresh White Mushrooms',
                'slug' => Str::slug('Fresh White Mushrooms'),
                'description' => 'Nấm trắng tươi, thích hợp cho các món xào, lẩu.',
                'price' => 28000,
                'sale_price' => null,
                'weight' => '200',
                'unit' => 'g',
                'stock_quantity' => 120,
                'view_count' => 0,
                'category_id' => 9,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Alpenliebe Creamy Caramel Candies',
                'slug' => Str::slug('Alpenliebe Creamy Caramel Candies'),
                'description' => 'Kẹo caramel mềm mịn, thơm ngọt tự nhiên.',
                'price' => 18000,
                'sale_price' => null,
                'weight' => '108',
                'unit' => 'g',
                'stock_quantity' => 250,
                'view_count' => 0,
                'category_id' => 30,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Frozen Shrimp – Peeled (Size 31/40)',
                'slug' => Str::slug('Frozen Shrimp – Peeled (Size 31/40)'),
                'description' => 'Tôm bóc vỏ đông lạnh, tiện lợi, giàu dinh dưỡng.',
                'price' => 160000,
                'sale_price' => 149000,
                'weight' => '500',
                'unit' => 'g',
                'stock_quantity' => 90,
                'view_count' => 0,
                'category_id' => 15,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Canned Tuna – Ayam Brand in Sunflower Oil',
                'slug' => Str::slug('Canned Tuna – Ayam Brand in Sunflower Oil'),
                'description' => 'Cá ngừ đóng hộp với dầu hướng dương, thơm ngon.',
                'price' => 36000,
                'sale_price' => null,
                'weight' => '150',
                'unit' => 'g',
                'stock_quantity' => 80,
                'view_count' => 0,
                'category_id' => 17,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Potatoes (Khoai tây Đà Lạt)',
                'slug' => Str::slug('Potatoes (Khoai tây Đà Lạt)'),
                'description' => 'Khoai tây tươi từ Đà Lạt, sạch, giàu tinh bột.',
                'price' => 18000,
                'sale_price' => null,
                'weight' => '1',
                'unit' => 'kg',
                'stock_quantity' => 150,
                'view_count' => 0,
                'category_id' => 8,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Sweet Corn Kernels – Frozen',
                'slug' => Str::slug('Sweet Corn Kernels – Frozen'),
                'description' => 'Bắp ngọt đông lạnh, dễ chế biến, giữ nguyên vị.',
                'price' => 25000,
                'sale_price' => null,
                'weight' => '500',
                'unit' => 'g',
                'stock_quantity' => 100,
                'view_count' => 0,
                'category_id' => 19,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Ajinomoto Iodized Salt 500g',
                'slug' => Str::slug('Ajinomoto Iodized Salt 500g'),
                'description' => 'Muối i-ốt Ajinomoto, hạt mịn, tiện lợi.',
                'price' => 9000,
                'sale_price' => null,
                'weight' => '500',
                'unit' => 'g',
                'stock_quantity' => 500,
                'view_count' => 0,
                'category_id' => 27,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Danisa Butter Cookies – Danish',
                'slug' => Str::slug('Danisa Butter Cookies – Danish'),
                'description' => 'Bánh quy bơ Danisa nhập khẩu, thơm ngon đặc trưng.',
                'price' => 125000,
                'sale_price' => 115000,
                'weight' => '454',
                'unit' => 'g',
                'stock_quantity' => 75,
                'view_count' => 0,
                'category_id' => 29,
                'status' => 1,
                'published_at' => now(),
            ],
            [
                'name' => 'Meizan Vegetable Cooking Oil 1L',
                'slug' => Str::slug('Meizan Vegetable Cooking Oil 1L'),
                'description' => 'Dầu thực vật Meizan 1L, giàu Vitamin E.',
                'price' => 49000,
                'sale_price' => null,
                'weight' => '1',
                'unit' => 'l',
                'stock_quantity' => 200,
                'view_count' => 0,
                'category_id' => 25,
                'status' => 1,
                'published_at' => now(),
            ],
        ];

        foreach ($products as &$product) {
            $product['created_at'] = now();
            $product['updated_at'] = now();
        }

        DB::table('products')->insert($products);
    }
}
