<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductDetailSeeder extends Seeder
{
    public function run(): void
    {
        $details = [
            [
                'brand' => 'VinEco',
                'expiry' => '5 days',
                'weight_detail' => '200g (hữu cơ)',
                'packaging_type' => 'Túi nhựa PE',
                'warranty_period' => null,
                'registration_number' => 'VECO-SPIN-2024',
                'serial_number' => 'VE-001',
                'manufacturer_name' => 'VinEco Farm',
                'shipped_from' => 'Hà Nội',
            ],
            [
                'brand' => 'Marine Harvest',
                'expiry' => '7 days',
                'weight_detail' => '300g (phi lê)',
                'packaging_type' => 'Khay nhựa hút chân không',
                'warranty_period' => null,
                'registration_number' => 'MH-SALMON-2024',
                'serial_number' => 'MH-002',
                'manufacturer_name' => 'Marine Harvest Norway',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'USDA Choice',
                'expiry' => '5 days',
                'weight_detail' => '500g (steak cắt sẵn)',
                'packaging_type' => 'Túi hút chân không',
                'warranty_period' => null,
                'registration_number' => 'USDA-BEEF-2024',
                'serial_number' => 'US-003',
                'manufacturer_name' => 'Nebraska Beef Co.',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'Tropicana',
                'expiry' => '2025-02-01',
                'weight_detail' => '1L (chai nhựa)',
                'packaging_type' => 'Chai PET',
                'warranty_period' => null,
                'registration_number' => 'TRO-100OJ-2024',
                'serial_number' => 'TR-004',
                'manufacturer_name' => 'PepsiCo VN',
                'shipped_from' => 'Bình Dương',
            ],
            [
                'brand' => 'Vinamilk',
                'expiry' => '2025-01-15',
                'weight_detail' => '1L (không đường)',
                'packaging_type' => 'Hộp giấy tiệt trùng',
                'warranty_period' => null,
                'registration_number' => 'VNM-MILK-2024',
                'serial_number' => 'VNM-005',
                'manufacturer_name' => 'Vinamilk',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'Omachi',
                'expiry' => '2025-12-30',
                'weight_detail' => '80g (1 gói)',
                'packaging_type' => 'Bao bì nilon',
                'warranty_period' => null,
                'registration_number' => 'OMA-007',
                'serial_number' => 'OMA-006',
                'manufacturer_name' => 'Masan Consumer',
                'shipped_from' => 'Đồng Nai',
            ],
            [
                'brand' => 'CP Vietnam',
                'expiry' => '4 days',
                'weight_detail' => '500g (thịt ba rọi)',
                'packaging_type' => 'Khay xốp bọc màng PE',
                'warranty_period' => null,
                'registration_number' => 'CP-PORK-2024',
                'serial_number' => 'CP-007',
                'manufacturer_name' => 'C.P Vietnam',
                'shipped_from' => 'Đồng Nai',
            ],
            [
                'brand' => 'Oreo',
                'expiry' => '2025-10-10',
                'weight_detail' => '137g (bánh quy)',
                'packaging_type' => 'Bao bì nilon in màu',
                'warranty_period' => null,
                'registration_number' => 'OREO-2024',
                'serial_number' => 'OR-008',
                'manufacturer_name' => 'Mondelez International',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'VinEco',
                'expiry' => '5 days',
                'weight_detail' => '200g (Cải xoăn)',
                'packaging_type' => 'Túi nhựa đục lỗ',
                'warranty_period' => null,
                'registration_number' => 'VECO-KALE-2024',
                'serial_number' => 'VE-009',
                'manufacturer_name' => 'VinEco Farm',
                'shipped_from' => 'Hà Nội',
            ],
            [
                'brand' => 'CP Vietnam',
                'expiry' => '5 days',
                'weight_detail' => '500g (ức gà phi lê)',
                'packaging_type' => 'Khay xốp bọc PE',
                'warranty_period' => null,
                'registration_number' => 'CP-CHICK-2024',
                'serial_number' => 'CP-010',
                'manufacturer_name' => 'C.P Vietnam',
                'shipped_from' => 'Đồng Nai',
            ],
            [
                'brand' => 'G7',
                'expiry' => '2026-01-01',
                'weight_detail' => '240g (16 gói)',
                'packaging_type' => 'Hộp giấy + túi nhỏ',
                'warranty_period' => null,
                'registration_number' => 'G7-3IN1-2024',
                'serial_number' => 'G7-011',
                'manufacturer_name' => 'Trung Nguyên',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'VietFarm',
                'expiry' => '4 days',
                'weight_detail' => '200g (nấm trắng tươi)',
                'packaging_type' => 'Khay nhựa màng PE',
                'warranty_period' => null,
                'registration_number' => 'VF-MUSHROOM-2024',
                'serial_number' => 'VF-012',
                'manufacturer_name' => 'VietFarm',
                'shipped_from' => 'Đà Lạt',
            ],
            [
                'brand' => 'Alpenliebe',
                'expiry' => '2026-03-01',
                'weight_detail' => '108g (kẹo caramel)',
                'packaging_type' => 'Túi nhựa có zipper',
                'warranty_period' => null,
                'registration_number' => 'AL-CANDY-2024',
                'serial_number' => 'AL-013',
                'manufacturer_name' => 'Perfetti Van Melle',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'Vĩnh Hoàn',
                'expiry' => '6 months (frozen)',
                'weight_detail' => '500g (tôm đông lạnh)',
                'packaging_type' => 'Túi PE đông lạnh',
                'warranty_period' => null,
                'registration_number' => 'VH-SHRIMP-2024',
                'serial_number' => 'VH-014',
                'manufacturer_name' => 'Vĩnh Hoàn Seafood',
                'shipped_from' => 'Cần Thơ',
            ],
            [
                'brand' => 'Ayam Brand',
                'expiry' => '2027-01-01',
                'weight_detail' => '150g (cá ngừ)',
                'packaging_type' => 'Lon thiếc',
                'warranty_period' => null,
                'registration_number' => 'AYAM-TUNA-2024',
                'serial_number' => 'AY-015',
                'manufacturer_name' => 'Ayam Brand Malaysia',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'Đà Lạt GAP',
                'expiry' => '6 days',
                'weight_detail' => '1kg (khoai tây Đà Lạt)',
                'packaging_type' => 'Túi lưới',
                'warranty_period' => null,
                'registration_number' => 'DL-POTATO-2024',
                'serial_number' => 'DL-016',
                'manufacturer_name' => 'HTX Đà Lạt GAP',
                'shipped_from' => 'Lâm Đồng',
            ],
            [
                'brand' => 'Greenfarm',
                'expiry' => '12 months',
                'weight_detail' => '500g (bắp ngọt đông lạnh)',
                'packaging_type' => 'Túi zipper đông lạnh',
                'warranty_period' => null,
                'registration_number' => 'GF-CORN-2024',
                'serial_number' => 'GF-017',
                'manufacturer_name' => 'Greenfarm',
                'shipped_from' => 'Bình Dương',
            ],
            [
                'brand' => 'Ajinomoto',
                'expiry' => '2026-12-31',
                'weight_detail' => '500g (muối i-ốt)',
                'packaging_type' => 'Bao bì nhựa PP',
                'warranty_period' => null,
                'registration_number' => 'AJI-SALT-2024',
                'serial_number' => 'AJ-018',
                'manufacturer_name' => 'Ajinomoto Việt Nam',
                'shipped_from' => 'Long An',
            ],
            [
                'brand' => 'Danisa',
                'expiry' => '2026-05-10',
                'weight_detail' => '454g (hộp thiếc)',
                'packaging_type' => 'Hộp thiếc sang trọng',
                'warranty_period' => null,
                'registration_number' => 'DANISA-2024',
                'serial_number' => 'DA-019',
                'manufacturer_name' => 'Danisa Denmark',
                'shipped_from' => 'TP.HCM',
            ],
            [
                'brand' => 'Meizan',
                'expiry' => '2026-09-15',
                'weight_detail' => '1L (chai nhựa)',
                'packaging_type' => 'Chai PET',
                'warranty_period' => null,
                'registration_number' => 'MEI-OIL-2024',
                'serial_number' => 'ME-020',
                'manufacturer_name' => 'CALOFIC',
                'shipped_from' => 'Quảng Ninh',
            ],
        ];

        foreach ($details as $index => &$item) {
            $item['product_id'] = $index + 1;
            $item['created_at'] = now();
            $item['updated_at'] = now();
        }

        DB::table('product_details')->insert($details);
    }
}
